# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Vishal Patel
tagline:          'Fullstack developer'
description:      'Fullstack developer'
url:              http://hyde.getpoole.com
baseurl:          '/blog/'

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
  
params:
  themeColor: "theme-base-08"
